import type { Dictionary } from "./types";

export const de: Dictionary = {
  title: "Solarprognose",
  remaining: "REST",
  period: "ZEITRAUM",
  average: "Ø",
  perDay: "/Tag",
  today: "Heute",
  yesterday: "Gestern",
  tomorrow: "Morgen",
  produced: "Erzeugt",
  forecast: "Prognose",
  forecastAt19: "Prognose um 19:00",
  total: "Gesamt",
  productionNotConfigured:
    "Es wird nur die Restprognose angezeigt, weil kein Erzeugungssensor eingerichtet ist.",
  productionMissing: "Der eingerichtete Erzeugungssensor hat keinen gültigen Energiewert.",
  productionPercent: "Erzeugt: {percent}%",
  periodRestOnly:
    "Heute enthält nur die Restprognose, weil kein Erzeugungssensor eingerichtet ist.",
  periodHelp:
    "Der Zeitraum summiert die angezeigten Tage. Der Durchschnitt verwendet nur vollständige Tage.",
  periodIncomplete:
    "Die Summe ist gekennzeichnet, weil nicht jeder angezeigte Tag vollständig vorliegt.",
  approximate: "≈",
  sourcesPartial: "{count} von {total} Quellen liefern Daten.",
  dayPartial: "Die Prognosezeitreihe dieses Tages ist unvollständig.",
  noForecast: "Keine vollständige Solarprognose verfügbar.",
  incomplete: "Prognosedaten sind unvollständig.",
  warning: "Prognosewarnung",
  configuration: "Konfiguration",
  name: "Titel",
  language: "Sprache",
  languageAuto: "Automatisch (Home Assistant)",
  forecastProvider: "Prognoseanbieter",
  forecastProviderAuto: "Automatisch",
  forecastProviderForecastSolar: "Forecast.Solar",
  forecastProviderSolcast: "Solcast PV Forecast",
  productionTodayEntity: "Heutiger Erzeugungssensor",
  productionTodayHelp: "Optionaler Energiesensor für die gesamte heutige Erzeugung.",
  historyForecastEntity: "Historischer Prognosesensor",
  historyForecastHelp:
    "Setze diese Tagesprognose für den Folgetag mit dem heutigen Erzeugungssensor für den gestrigen Vergleich.",
  invalidLanguage: "Die gewählte Sprache ist nicht verfügbar. Englisch wird verwendet.",
  warningConnection: "Home Assistant ist nicht verbunden.",
  warningSources: "Prognosequellen können nicht erkannt werden.",
  warningForecast: "Eine Prognose ist nicht verfügbar.",
  warningIncomplete: "Prognosedaten sind unvollständig.",
  warningEnergy: "Ein Prognoseenergiewert ist ungültig.",
  warningProduction: "Der eingerichtete Erzeugungssensor ist ungültig.",
  warningHistory: "Der historische Erzeugungs- oder Prognosewert fehlt oder ist ungültig.",
  warningHistoryConfiguration:
    "Setze den heutigen Erzeugungssensor für den historischen Prognosesensor.",
  warningHistorySchema: "Die Home-Assistant-Historienantwort ist nicht kompatibel.",
  warningSchema:
    "Die Prognoseantwort ist nicht kompatibel. Prüfe die Kartenkompatibilität mit Home Assistant.",
  warningProviderInvalid: "Der gewählte Prognoseanbieter ist ungültig.",
  warningProviderUnavailable: "Der gewählte Prognoseanbieter ist nicht eingerichtet.",
  warningSolcastAmbiguous: "Es wurden mehrere aktivierte Solcast-Konfigurationen gefunden.",
  warningSolcastMode: "Der Solcast-Prognosemodus fehlt oder ist ungültig.",
};
