name: HACS validation

on:
  workflow_dispatch:

permissions: {}

jobs:
  validate-hacs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: hacs/action@main
        with:
          category: plugin
